import { Map as MapIcon, Phone, Truck, UserRound } from "lucide-react";

type Props = { bookings: any[]; onTrack: (booking: any) => void; onViewBookings: () => void };
const normalize = (value: string | undefined) => (value || "").toUpperCase().replace(/ /g, "_");
function Badge({ status }: { status: string }) { const value = normalize(status); const tone = ["DELIVERED", "COMPLETED"].includes(value) ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-blue-400/20 bg-blue-400/10 text-blue-300"; return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold tracking-[0.12em] ${tone}`}>{status?.replace(/_/g, " ")}</span>; }
export default function AssignedOperationsSection({ bookings, onTrack, onViewBookings }: Props) {
  const assigned = bookings.filter((booking) => booking.assigned_driver_name || booking.assigned_vehicle_registration);
  return <section className="assigned-operations rounded-xl border border-blue-500/20 bg-slate-900 p-5 shadow-lg sm:p-6"><div className="flex items-center gap-3"><span className="rounded-lg bg-blue-500/10 p-2 text-blue-400"><Truck size={18} /></span><div><h2 className="text-lg font-bold text-white">Assigned Operations</h2><p className="text-xs text-slate-500">Driver and vehicle details appear after CargoX dispatches your request.</p></div></div>{assigned.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{assigned.map((booking) => <article key={booking.id} className="rounded-xl border border-slate-800 bg-slate-950/60 p-4 transition hover:border-blue-500/30"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-blue-300">{booking.request_number}</p><p className="mt-2 text-sm text-slate-400">{booking.pickup_address} <span className="text-slate-700">to</span> {booking.destination_address}</p></div><Badge status={booking.status} /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-600">Assigned driver</p><div className="mt-2 flex items-start gap-2"><UserRound size={15} className="mt-0.5 text-blue-400" /><div><p className="text-sm font-semibold text-white">{booking.assigned_driver_name || "Driver contact unavailable"}</p>{booking.assigned_driver_phone ? <a href={`tel:${booking.assigned_driver_phone}`} className="mt-1 flex items-center gap-1 text-xs text-blue-300"><Phone size={12} />{booking.assigned_driver_phone}</a> : <p className="mt-1 text-xs text-slate-600">Driver contact unavailable</p>}</div></div></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-600">Vehicle</p><div className="mt-2 flex items-start gap-2"><Truck size={15} className="mt-0.5 text-cyan-400" /><div><p className="text-sm font-semibold text-white">{booking.assigned_vehicle_registration || "Vehicle unavailable"}</p><p className="mt-1 text-xs text-slate-500">{booking.assigned_vehicle_type || ""}{booking.assigned_vehicle_capacity_tons ? ` · ${booking.assigned_vehicle_capacity_tons} tons` : ""}</p></div></div></div></div><button onClick={() => onTrack(booking)} className="mt-5 flex items-center gap-2 rounded-lg bg-blue-500/10 px-3 py-2 text-xs font-bold text-blue-300 hover:bg-blue-500/20"><MapIcon size={14} />Track delivery</button></article>)}</div> : <div className="mt-5 flex flex-col items-center rounded-xl border border-dashed border-slate-700 bg-slate-950/40 px-5 py-8 text-center"><Truck className="text-slate-700" size={26} /><p className="mt-3 text-sm font-semibold text-slate-300">No driver assigned yet</p><p className="mt-1 max-w-md text-xs leading-5 text-slate-600">Your CargoX operations team will assign a vehicle and driver after reviewing your request.</p><button onClick={onViewBookings} className="mt-4 text-xs font-bold text-blue-400 hover:text-blue-300">View my bookings</button></div>}</section>;
}
