"""phase_9_system_hardening_and_notifications

Revision ID: 01b652e32e4f
Revises: a9f3c2d1e4b7
Create Date: 2026-09-16 20:35:20.134207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b652e32e4f'
down_revision: Union[str, Sequence[str], None] = 'a9f3c2d1e4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'MOCK_EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=True)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # Duplicate preflight check for invoices.request_id
    connection = op.get_bind()
    duplicates = connection.execute(
        sa.text("SELECT request_id, COUNT(*) FROM invoices GROUP BY request_id HAVING COUNT(*) > 1")
    ).fetchall()
    
    if duplicates:
        duplicate_ids = [str(r[0]) for r in duplicates]
        raise Exception(f"Migration failed: duplicate invoices found for request_ids: {duplicate_ids}. Please resolve manually before applying unique constraint.")
    
    op.create_unique_constraint('uq_invoices_request_id', 'invoices', ['request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoices_request_id', 'invoices', type_='unique')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
