"""phase 3 delivery request updates

Revision ID: 1a76e80e5c60
Revises: c30553a89715
Create Date: 2026-09-16 18:33:19.022239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a76e80e5c60'
down_revision: Union[str, Sequence[str], None] = 'c30553a89715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('delivery_requests_recipient_company_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_requests', 'recipient_companies', ['recipient_company_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('chk_weight_positive', 'delivery_requests', 'weight_tons > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_weight_positive', 'delivery_requests', type_='check')
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_requests_recipient_company_id_fkey'), 'delivery_requests', 'recipient_companies', ['recipient_company_id'], ['id'])
    # ### end Alembic commands ###
