"""Update notification model

Revision ID: 36acb04f8a0a
Revises: 9edbd14bb806
Create Date: 2026-08-17 22:00:19.541510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36acb04f8a0a'
down_revision: Union[str, Sequence[str], None] = '9edbd14bb806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('delivery_status', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_column('notifications', 'metadata_payload')
    op.drop_column('notifications', 'delivery_status')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'event_type')
    # ### end Alembic commands ###
