"""Add compliance document model

Revision ID: 744076949a23
Revises: d7f6ee4feb15
Create Date: 2026-09-16 22:30:13.616905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744076949a23'
down_revision: Union[str, Sequence[str], None] = 'd7f6ee4feb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('VEHICLE', 'DRIVER', name='documentownertype'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('DRIVING_LICENSE', 'MEDICAL_CERTIFICATE', 'REGISTRATION', 'INSURANCE', 'PUC', 'PERMIT', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'ARCHIVED', name='documentverificationstatus'), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_documents_id'), 'compliance_documents', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_documents_owner_id'), 'compliance_documents', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_documents_owner_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_id'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    # ### end Alembic commands ###
