"""phase_1_baseline

Revision ID: c30553a89715
Revises: 
Create Date: 2026-09-16 17:30:31.774653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30553a89715'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('billing_address', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='companystatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_companies_id'), 'customer_companies', ['id'], unique=False)
    op.create_index(op.f('ix_customer_companies_name'), 'customer_companies', ['name'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OPEN', 'CONTAINER', 'TRAILER', name='vehicletype'), nullable=False),
    sa.Column('capacity_tons', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'MAINTENANCE', 'ASSIGNED', name='vehiclestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_table('recipient_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_company_id'], ['customer_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipient_companies_id'), 'recipient_companies', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER_USER', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('customer_company_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_company_id'], ['customer_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('delivery_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(), nullable=False),
    sa.Column('customer_company_id', sa.UUID(), nullable=False),
    sa.Column('goods_type', sa.String(), nullable=False),
    sa.Column('goods_description', sa.String(), nullable=True),
    sa.Column('weight_tons', sa.Float(), nullable=False),
    sa.Column('special_instructions', sa.String(), nullable=True),
    sa.Column('pickup_company_name', sa.String(), nullable=False),
    sa.Column('pickup_address', sa.String(), nullable=False),
    sa.Column('pickup_contact_person', sa.String(), nullable=True),
    sa.Column('pickup_phone', sa.String(), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('recipient_company_id', sa.UUID(), nullable=True),
    sa.Column('destination_company_name', sa.String(), nullable=False),
    sa.Column('destination_address', sa.String(), nullable=False),
    sa.Column('destination_contact_person', sa.String(), nullable=True),
    sa.Column('destination_phone', sa.String(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'QUOTED', 'ACCEPTED', 'VEHICLE_ASSIGNED', 'DRIVER_ASSIGNED', 'PICKUP_IN_PROGRESS', 'IN_TRANSIT', 'ARRIVED', 'POD_SUBMITTED', 'DELIVERED', 'COMPLETED', 'REJECTED', 'CUSTOMER_CANCELLED', name='deliveryrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_company_id'], ['customer_companies.id'], ),
    sa.ForeignKeyConstraint(['recipient_company_id'], ['recipient_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_requests_id'), 'delivery_requests', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_requests_request_number'), 'delivery_requests', ['request_number'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'OFF_DUTY', name='driverstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('pricing_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_rate_per_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_per_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_configs_id'), 'pricing_configs', ['id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('pricing_config_id', sa.UUID(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_rate_per_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('internal_base_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cargox_margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_total_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='quotationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_config_id'], ['pricing_configs.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['delivery_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('pickup_started_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['delivery_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('customer_company_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', name='invoicestatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_company_id'], ['customer_companies.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['delivery_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('proof_of_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_phone', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_of_deliveries_id'), 'proof_of_deliveries', ['id'], unique=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_id'), 'vehicle_assignments', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'CASH', 'UPI', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_vehicle_assignments_id'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_proof_of_deliveries_id'), table_name='proof_of_deliveries')
    op.drop_table('proof_of_deliveries')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_pricing_configs_id'), table_name='pricing_configs')
    op.drop_table('pricing_configs')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_delivery_requests_request_number'), table_name='delivery_requests')
    op.drop_index(op.f('ix_delivery_requests_id'), table_name='delivery_requests')
    op.drop_table('delivery_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipient_companies_id'), table_name='recipient_companies')
    op.drop_table('recipient_companies')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_customer_companies_name'), table_name='customer_companies')
    op.drop_index(op.f('ix_customer_companies_id'), table_name='customer_companies')
    op.drop_table('customer_companies')
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS paymentmethod")
    op.execute("DROP TYPE IF EXISTS invoicestatus")
    op.execute("DROP TYPE IF EXISTS quotationstatus")
    op.execute("DROP TYPE IF EXISTS deliveryrequeststatus")
    op.execute("DROP TYPE IF EXISTS driverstatus")
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS vehiclestatus")
    op.execute("DROP TYPE IF EXISTS vehicletype")
    op.execute("DROP TYPE IF EXISTS companystatus")
    # ### end Alembic commands ###
