"""Add location_histories table

Revision ID: d6b677d1bb2f
Revises: 744076949a23
Create Date: 2026-09-18 01:24:56.935506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b677d1bb2f'
down_revision: Union[str, Sequence[str], None] = '744076949a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_histories_id'), 'location_histories', ['id'], unique=False)
    op.create_index('ix_location_histories_trip_recorded', 'location_histories', ['trip_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_histories_trip_recorded', table_name='location_histories')
    op.drop_index(op.f('ix_location_histories_id'), table_name='location_histories')
    op.drop_table('location_histories')
    # ### end Alembic commands ###
