"""Add DriverSettlement

Revision ID: d7f6ee4feb15
Revises: dd1d5071f9a3
Create Date: 2026-09-16 21:26:26.265744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f6ee4feb15'
down_revision: Union[str, Sequence[str], None] = 'dd1d5071f9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUMs manually because alembic autogenerate doesn't do it reliably for Postgres when adding columns
    op.execute("CREATE TYPE expensepayer AS ENUM ('CARGOX', 'DRIVER')")

    op.create_table('driver_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('base_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reimbursements', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction_reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PAID', 'CANCELLED', name='settlementstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.CheckConstraint('base_pay >= 0', name='chk_settlement_base_pay'),
    sa.CheckConstraint('deductions >= 0', name='chk_settlement_deductions'),
    sa.CheckConstraint('reimbursements >= 0', name='chk_settlement_reimbursements'),
    sa.CheckConstraint('total_payout >= 0', name='chk_total_payout'),
    sa.CheckConstraint('deductions = 0 OR deduction_reason IS NOT NULL', name='chk_deduction_reason'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index(op.f('ix_driver_settlements_driver_id'), 'driver_settlements', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_settlements_id'), 'driver_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_driver_settlements_status'), 'driver_settlements', ['status'], unique=False)
    op.add_column('trip_expenses', sa.Column('paid_by', sa.Enum('CARGOX', 'DRIVER', name='expensepayer'), nullable=False))
    op.add_column('trips', sa.Column('settlement_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trips_settlement_id'), 'trips', ['settlement_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'driver_settlements', ['settlement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_settlement_id'), table_name='trips')
    op.drop_column('trips', 'settlement_id')
    op.drop_column('trip_expenses', 'paid_by')
    op.drop_index(op.f('ix_driver_settlements_status'), table_name='driver_settlements')
    op.drop_index(op.f('ix_driver_settlements_id'), table_name='driver_settlements')
    op.drop_index(op.f('ix_driver_settlements_driver_id'), table_name='driver_settlements')
    op.drop_table('driver_settlements')
    # ### end Alembic commands ###
