"""phase 10 fleet expenses and maintenance

Revision ID: dd1d5071f9a3
Revises: 01b652e32e4f
Create Date: 2026-09-16 21:00:39.856392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1d5071f9a3'
down_revision: Union[str, Sequence[str], None] = '01b652e32e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_maintenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('ROUTINE', 'REPAIR', 'INSPECTION', name='maintenancetype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatus'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mechanic_notes', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.CheckConstraint('cost > 0 OR cost IS NULL', name='chk_maintenance_cost_positive'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenance_id'), 'vehicle_maintenance', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_maintenance_type'), 'vehicle_maintenance', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_status'), 'vehicle_maintenance', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_vehicle_id'), 'vehicle_maintenance', ['vehicle_id'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FUEL', 'TOLL', 'DRIVER_ALLOWANCE', 'MAINTENANCE_INCIDENTAL', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='expensestatus'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.CheckConstraint("receipt_url LIKE 'https://%%' OR receipt_url IS NULL", name='chk_receipt_url_https'),
    sa.CheckConstraint('amount > 0', name='chk_expense_amount_positive'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_category'), 'trip_expenses', ['category'], unique=False)
    op.create_index(op.f('ix_trip_expenses_id'), 'trip_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_trip_expenses_status'), 'trip_expenses', ['status'], unique=False)
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_status'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_category'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_vehicle_maintenance_vehicle_id'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_status'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_maintenance_type'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_id'), table_name='vehicle_maintenance')
    op.drop_table('vehicle_maintenance')
    # ### end Alembic commands ###
