"""Add tracking models and latlng

Revision ID: f69d2e77d411
Revises: e1bacdd62150
Create Date: 2026-08-15 18:13:48.068273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69d2e77d411'
down_revision: Union[str, Sequence[str], None] = 'e1bacdd62150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_updates_id'), 'location_updates', ['id'], unique=False)
    op.create_table('proof_of_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=False),
    sa.Column('signature_url', sa.String(), nullable=False),
    sa.Column('delivery_image_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_index(op.f('ix_proof_of_delivery_id'), 'proof_of_delivery', ['id'], unique=False)
    op.add_column('bookings', sa.Column('pickup_address', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('drop_address', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('drop_latitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('drop_longitude', sa.Float(), nullable=True))
    op.drop_column('bookings', 'pickup_location')
    op.drop_column('bookings', 'drop_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('drop_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('pickup_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'drop_longitude')
    op.drop_column('bookings', 'drop_latitude')
    op.drop_column('bookings', 'drop_address')
    op.drop_column('bookings', 'pickup_longitude')
    op.drop_column('bookings', 'pickup_latitude')
    op.drop_column('bookings', 'pickup_address')
    op.drop_index(op.f('ix_proof_of_delivery_id'), table_name='proof_of_delivery')
    op.drop_table('proof_of_delivery')
    op.drop_index(op.f('ix_location_updates_id'), table_name='location_updates')
    op.drop_table('location_updates')
    # ### end Alembic commands ###
