"""Add phase 7 indexes and constraints

Revision ID: f8b03f8662e9
Revises: 36acb04f8a0a
Create Date: 2026-09-15 22:58:43.469216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b03f8662e9'
down_revision: Union[str, Sequence[str], None] = '36acb04f8a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_customer_id', 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_check_constraint('check_cargo_weight_positive', 'bookings', 'cargo_weight >= 0')
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_check_constraint('check_invoice_amount_paid_positive', 'invoices', 'amount_paid >= 0')
    op.create_check_constraint('check_invoice_base_charge_positive', 'invoices', 'base_charge >= 0')
    op.create_check_constraint('check_invoice_taxes_positive', 'invoices', 'taxes >= 0')
    op.create_check_constraint('check_invoice_total_amount_positive', 'invoices', 'total_amount >= 0')
    op.create_index('ix_trips_booking_id', 'trips', ['booking_id'], unique=False)
    op.create_index('ix_trips_driver_id', 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_status', 'trips', ['status'], unique=False)
    op.create_index('ix_trips_vehicle_id', 'trips', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trips_vehicle_id', table_name='trips')
    op.drop_index('ix_trips_status', table_name='trips')
    op.drop_index('ix_trips_driver_id', table_name='trips')
    op.drop_index('ix_trips_booking_id', table_name='trips')
    op.drop_constraint('check_invoice_total_amount_positive', 'invoices', type_='check')
    op.drop_constraint('check_invoice_taxes_positive', 'invoices', type_='check')
    op.drop_constraint('check_invoice_base_charge_positive', 'invoices', type_='check')
    op.drop_constraint('check_invoice_amount_paid_positive', 'invoices', type_='check')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_constraint('check_cargo_weight_positive', 'bookings', type_='check')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_customer_id', table_name='bookings')
    # ### end Alembic commands ###
